---
title: "Figure Sizes"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(shiny)
```

Column
-----------------------------------------------------------------------

### Chart 1 (12, 7)

```{r, fig.width=12, fig.height=7}
plot(cars)
```

Column
-----------------------------------------------------------------------

### Chart 2 (5, 5)

```{r, fig.width=5, fig.height=5}
plot(pressure)
```

### Chart 3 (10, 7)

```{r, fig.width=10, fig.height=7}
plot(airmiles)
```

### Table 1 (knitr - kable)
``` {r}
kable(mtcars)
```

### Table 2 (shiny - renderTable)
``` {r}
renderTable({
  head(mtcars, 10)
})
```

### Table 3 (DT)
``` {r}
DT::datatable(mtcars,
              options=list(pageLength=25,
                           bPaginate=T),
              filter="top")
```

### Table 4 (DT - renderDataTable)
```{r}
DT::renderDataTable({
  data <- head(mtcars, n=10)
  DT::datatable(data, options = list(
    bPaginate = FALSE
  ))
})
```